package com.storium.data.features.product.local.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.room.TypeConverters
import com.storium.data.features.product.local.dao.ProductsDao
import com.storium.data.features.product.local.entity.CategoryEntity
import com.storium.data.features.product.local.entity.ProductEntity
import com.storium.data.features.product.local.entity.ReviewEntity
import com.storium.data.local.converter.StringListConverter

@Database(
    entities = [ProductEntity::class, CategoryEntity::class, ReviewEntity::class],
    version = 1,
    exportSchema = false,
)
@TypeConverters(StringListConverter::class)
@ConstructedBy(ProductsDatabaseConstructor::class)
abstract class ProductsDatabase : RoomDatabase() {
    abstract fun productsDao(): ProductsDao
}

// The missing actual implementation is generated by Room KSP at compile time
@Suppress("NO_ACTUAL_FOR_EXPECT")
expect object ProductsDatabaseConstructor : RoomDatabaseConstructor<ProductsDatabase>
