#!/bin/sh

echo "Running static analysis..."

./gradlew :shared:detektAndroidMain :shared:detektIosArm64Main :shared:detektIosSimulatorArm64Main :androidApp:detekt --no-daemon

status=$?

if [ "$status" = 0 ] ; then
    echo "Static analysis found no issues. Proceeding with push."
    exit 0
else
    echo 1>&2 "Static analysis found issues you need to fix before pushing."
    exit 1
fi
